name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    container:
      image: docker:29.5.3-dind-rootless
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5

      - name: CI
        run: ./ci.sh

     