name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: CI
        run: |
          ARGS="--registry ghcr.io/${{ github.repository }}"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ARGS="$ARGS --pull-request ${{ github.event.pull_request.number }}"
          fi
          ./ci.sh $ARGS

     